apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharedidp
  namespace: argocd
spec:
  project: project-portal
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-portal
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 1.2.0
    chart: sharedidp
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            keycloak:
              extraVolumes:
                - name: themes-catenax-shared
                  emptyDir: {}
                - name: themes-catenax-shared-portal
                  emptyDir: {}
                - name: realms
                  emptyDir: {}
                - name: realm-secrets
                  secret:
                    secretName: secret-sharedidp-realms
              extraVolumeMounts:
                - name: themes-catenax-shared
                  mountPath: "/opt/bitnami/keycloak/themes/catenax-shared"
                - name: themes-catenax-shared-portal
                  mountPath: "/opt/bitnami/keycloak/themes/catenax-shared-portal"
                - name: realms
                  mountPath: "/realms"
                - name: realm-secrets
                  mountPath: "/secrets"
              initContainers:
                - name: import
                  image: tractusx/portal-iam-consortia:v1.2.0
                  imagePullPolicy: Always
                  command:
                    - sh
                  args:
                    - -c
                    - |
                      echo "Copying themes-catenax-shared..."
                      cp -R /import/themes/catenax-shared/* /themes-catenax-shared
                      echo "Copying themes-catenax-shared-portal..."
                      cp -R /import/themes/catenax-shared-portal/* /themes-catenax-shared-portal
                      echo "Copying realms..."
                      cp -R /import/catenax-shared/stable/realms/* /realms
                      echo "Copying realms-secrets..."
                      cp /secrets/* /realms
                  volumeMounts:
                  - name: themes-catenax-shared
                    mountPath: "/themes-catenax-shared"
                  - name: themes-catenax-shared-portal
                    mountPath: "/themes-catenax-shared-portal"
                  - name: realms
                    mountPath: "/realms"
                  - name: realm-secrets
                    mountPath: "/secrets"
              ingress:
                enabled: true
                ingressClassName: nginx
                hostname: sharedidp.stable.demo.catena-x.net
                annotations:
                  cert-manager.io/cluster-issuer: letsencrypt-prod
                  nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
                  nginx.ingress.kubernetes.io/cors-allow-methods: PUT, GET, POST, OPTIONS
                  nginx.ingress.kubernetes.io/cors-allow-origin: https://sharedidp.stable.demo.catena-x.net, http://localhost:3000
                  nginx.ingress.kubernetes.io/enable-cors: "true"
                  nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
                  nginx.ingress.kubernetes.io/proxy-buffering: "on"
                  nginx.ingress.kubernetes.io/proxy-buffers-number: "20"
                  nginx.ingress.kubernetes.io/use-regex: "true"
                tls: true
            secrets:
              auth:
                existingSecret:
                  adminpassword: "<path:portal/data/stable/iam/sharedidp-keycloak#admin-password>"
                  managementpassword: "<path:portal/data/stable/iam/sharedidp-keycloak#management-password>"
              postgresql:
                auth:
                  existingSecret:
                    postgrespassword: "<path:portal/data/stable/iam/sharedidp-postgres#postgres-password>"
                    password: "<path:portal/data/stable/iam/sharedidp-postgres#password>"
                    replicationPassword: "<path:portal/data/stable/iam/sharedidp-postgres#replication-password>"
              realmuser:
                enabled: true
                cxtestaccessuser: "<path:portal/data/iam/sharedidp-user#CX-Test-Access-users-0.json>"
                company1user: "<path:portal/data/iam/sharedidp-user#Company-1-users-0.json>"
                company2user: "<path:portal/data/iam/sharedidp-user#Company-2-users-0.json>"
                securitycompany: "<path:portal/data/iam/sharedidp-user#Security-Company-users-0.json>"
                cxoperator: "<path:portal/data/iam/sharedidp-user#CX-Operator-users-0.json>"
                serviceprovider: "<path:portal/data/iam/sharedidp-user#Service-Provider-users-0.json>"
                appprovider: "<path:portal/data/iam/sharedidp-user#App-Provider-users-0.json>"
                chart: sharedidp
