apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tx-edc-registry-stable-b
  namespace: argocd
spec:
  project: project-traceability-foss
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-traceability-foss
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 0.5.0
    chart: tractusx-connector
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            install:
              postgresql: true
              vault: false
            enabled: true
            nameOverride: "tx-edc-provider-stable-b"
            fullnameOverride: "tx-edc-provider-stable-b"
            participant:
              id: BPNL00000003CNKC
            controlplane:
              ingresses:
                - enabled: true
                  hostname: "trace-x-edc-stable-b.stable.demo.catena-x.net"
                  annotations:
                    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
                    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
                    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                  endpoints:
                    - protocol
                    - management
                  tls:
                    enabled: true
                    secretName: tls-secret
              ssi:
                miw:
                  url: '<path:traceability-foss/data/stable-b/edc/wallet#ssi.miw.url>'
                  authorityId: '<path:traceability-foss/data/stable-b/edc/wallet#ssi.miw.authorityId>'
                oauth:
                  tokenurl: '<path:traceability-foss/data/stable-b/edc/wallet#ssi.oauth.tokenurl>'
                  client:
                    id: '<path:traceability-foss/data/stable-b/edc/wallet#ssi.oauth.client.id>'
                    secretAlias: edc-miw-keycloak-secret-stable-b
              endpoints:
                management:
                  authKey: '<path:traceability-foss/data/stable-b/edc/controlplane#edc.api.control.auth.apikey.value>'
              resources:
                limits:
                  cpu: 400m
                  memory: 1.5Gi
                requests:
                  cpu: 200m
                  memory: 1.5Gi
            dataplane:
              ingresses:
                - enabled: true
                  hostname: "trace-x-edc-stable-b-dataplane.stable.demo.catena-x.net"
                  annotations:
                    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
                    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
                    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                  endpoints:
                    - public
                  className: "nginx"
                  tls:
                    enabled: true
                    secretName: tls-secret

              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 512Mi

            backendService:
              httpProxyTokenReceiverUrl: "https://traceability-stable-b.stable.demo.catena-x.net/api/callback/endpoint-data-reference"

            postgresql:
              enabled: true
              auth:
                username: '<path:traceability-foss/data/stable-b/edc/database#user>'
                password: '<path:traceability-foss/data/stable-b/edc/database#password>'
              username: '<path:traceability-foss/data/stable-b/edc/database#user>'
              password: '<path:traceability-foss/data/stable-b/edc/database#password>'
              jdbcUrl: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/edc"

            vault:
              hashicorp:
                url: "https://vault.demo.catena-x.net"
                token: '<path:traceability-foss/data/stable-b/edc#edc.vault.hashicorp.token>'
                timeout: 30
                healthCheck:
                  enabled: true
                  standbyOk: true
                paths:
                  secret: /v1/traceability-foss
                  health: /v1/sys/health
              secretNames:
                transferProxyTokenSignerPrivateKey: daps-cert-key-stable-b
                transferProxyTokenSignerPublicKey: daps-cert-stable-b
                transferProxyTokenEncryptionAesKey: token-signer-aes-key

