apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iam
spec:
  project: project-portal
  source:
    repoURL: 'https://github.com/catenax-ng/catena-x-release-deployment'
    path: pre-prod/iam
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-portal
  syncPolicy:
    automated: {}
