apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-identity-wallets
spec:
  project: project-managed-identity-wallets
  source:
    repoURL: 'https://github.com/catenax-ng/catena-x-release-deployment'
    path: pre-prod/managed-identity-wallets
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-managed-identity-wallets
  syncPolicy:
    automated: {}
