apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bpdm
spec:
  project: project-bpdm
  source:
    repoURL: 'https://github.com/catenax-ng/catena-x-release-deployment'
    path: pre-prod/bpdm
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-bpdm
  syncPolicy:
    automated: {}
