apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sldt
spec:
  project: project-sldt
  source:
    repoURL: 'https://github.com/catenax-ng/catena-x-release-deployment'
    path: pre-prod/sldt
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-sldt
  syncPolicy:
    automated: {}
