registry:
  registry:
    image: ghcr.io/catenax-ng/registry:0.2.0-M2-multi-tenancy
    imagePullSecrets:
      - name: machineuser-pull-secret-ro
    host: semantics.pre-prod.demo.catena-x.net
    ingress:
      enabled: true
      tls: true
      urlPrefix: /registry
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/use-regex: "true"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
        nginx.ingress.kubernetes.io/x-forwarded-prefix: /registry
