apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dpp-edc-provider
  namespace: argocd
spec:
  project: project-material-pass
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-material-pass
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 0.5.0
    chart: tractusx-connector
    helm:
      valueFiles:
        - values.yaml
      values: |
        participant:
          id: "BPNL00000000CBA5"

        controlplane:
          enabled: true
          endpoints:
            # -- default api for health checks, should not be added to any ingress
            default:
              # -- port for incoming api calls
              port: 8080
              # -- path for incoming api calls
              path: /BPNL000000000000/api
            # -- data management api, used by internal users, can be added to an ingress and must not be internet facing
            management:
              # -- port for incoming api calls
              port: 8081
              # -- path for incoming api calls
              path: /BPNL000000000000/management
              # -- authentication key, must be attached to each 'X-Api-Key' request header
              authKey: password
            # -- control api, used for internal control calls. can be added to the internal ingress, but should probably not
            control:
              # -- port for incoming api calls
              port: 8083
              # -- path for incoming api calls
              path: /BPNL000000000000/control
            # -- ids api, used for inter connector communication and must be internet facing
            protocol:
              # -- port for incoming api calls
              port: 8084
              # -- path for incoming api calls
              path: /BPNL000000000000/api/v1/dsp
            # -- metrics api, used for application metrics, must not be internet facing
            metrics:
              # -- port for incoming api calls
              port: 9090
              # -- path for incoming api calls
              path: /BPNL000000000000/metrics
            # -- observability api with unsecured access, must not be internet facing
            observability:
              # -- port for incoming API calls
              port: 8085
              # -- observability api, provides /health /readiness and /liveness endpoints
              path: /BPNL000000000000/observability
              # -- allow or disallow insecure access, i.e. access without authentication
              insecure: true

          ssi:
            miw:
              url: "https://managed-identity-wallets-new-23-12.stable.demo.catena-x.net"
              authorityId: "BPNL00000003CRHK"
            oauth:
              tokenurl: "https://centralidp-23-12.stable.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
              client:
                id: "sa3"
                secretAlias: "stable-client-secret"
            endpoint:
              audience: https://materialpass-23-12.stable.demo.catena-x.net/consumer

          ## Ingress declaration to expose the network service.
          ingresses:
            ## Public / Internet facing Ingress
            - enabled: true
              # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
              hostname: "materialpass-23-12.stable.demo.catena-x.net"
              # -- Additional ingress annotations to add
              annotations: {}
              # -- EDC endpoints exposed by this ingress resource
              endpoints:
                - default
                - management
                - control
                - protocol
                - metrics
                - observability
              # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
              className: "nginx"
              # -- TLS [tls class](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) applied to the ingress resource
              tls:
                # -- Enables TLS on the ingress resource
                enabled: true
                # -- If present overwrites the default secret name
                secretName: "tls-secret"
        dataplane:
          enabled: true
          endpoints:
            default:
              port: 8080
              path: /BPNL000000000000/api
            public:
              port: 8081
              path: /BPNL000000000000/api/public
            control:
              port: 8083
              path: /BPNL000000000000/api/dataplane/control
            proxy:
              port: 8186
              path: /BPNL000000000000/proxy
            observability:
              # -- port for incoming API calls
              port: 8085
              # -- observability api, provides /health /readiness and /liveness endpoints
              path: /BPNL000000000000/observability
              # -- allow or disallow insecure access, i.e. access without authentication
              insecure: true
            metrics:
              port: 9090
              path: /BPNL000000000000/metrics

          ## Ingress declaration to expose the network service.
          ingresses:
            ## Public / Internet facing Ingress
            - enabled: true
              # -- The hostname to be used to precisely map incoming traffic onto the underlying network service
              hostname: "materialpass-23-12.stable.demo.catena-x.net"
              # -- Additional ingress annotations to add
              annotations: {}
              # -- EDC endpoints exposed by this ingress resource
              endpoints:
                - public
              # -- Defines the [ingress class](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class)  to use
              className: "nginx"
              # -- TLS [tls class](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) applied to the ingress resource
              tls:
                # -- Enables TLS on the ingress resource
                enabled: true
                # -- If present overwrites the default secret name
                secretName: "tls-secret"
              ## Adds [cert-manager](https://cert-manager.io/docs/) annotations to the ingress resource
              certManager:
                # -- If preset enables certificate generation via cert-manager namespace scoped issuer
                issuer: ""
                # -- If preset enables certificate generation via cert-manager cluster-wide issuer
                clusterIssuer: ""

        postgresql:
          username: dpp_user
          password: dpp_password


        vault:
          hashicorp:
            url: https://vault.demo.catena-x.net
            token: s.nMWRzBOSupUC5iXyANzHC7Zo
            paths:
              secret:  /v1/material-pass
              health: /v1/sys/health
          secretNames:
            transferProxyTokenSignerPrivateKey: ids-daps_key
            transferProxyTokenSignerPublicKey: ids-daps_crt
            transferProxyTokenEncryptionAesKey: edc-encryption-key

        backendService:
            httpProxyTokenReceiverUrl: "https://materialpass-23-12.stable.demo.catena-x.net/endpoint"
  syncPolicy:
    syncOptions:
      - Replace=true
