apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ids-sdf
  namespace: argocd
spec:
  project: project-essential-services
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-essential-services
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 2.1.7
    chart: sdfactory
    helm:
      parameters:
      parameters:
        - name: sdfactory.secret.authServerUrl
          value: 'https://centralidp.stable.demo.catena-x.net/auth'
        - name: sdfactory.secret.clearingHouseClientId
          value: <path:essential-services/data/custodian-stable#clearingHouse-clientId>
        - name: sdfactory.secret.clearingHouseClientSecret
          value: <path:essential-services/data/custodian-stable#clearingHouse-clientSecret>
        - name: sdfactory.secret.clearingHouseRealm
          value: <path:essential-services/data/custodian-stable#clearingHouse-realm>
        - name: sdfactory.secret.clearingHouseServerUrl
          value: <path:essential-services/data/custodian-stable#clearingHouse-serverUrl>
        - name: sdfactory.secret.clearingHouseUri
          value: <path:essential-services/data/custodian-stable#clearingHouse-uri>
        - name: sdfactory.secret.clientId
          value: <path:essential-services/data/custodian-stable#clientId>
        - name: sdfactory.secret.clientSecret
          value: <path:essential-services/data/custodian-stable#clientSecret>
        - name: sdfactory.secret.custodianWalletUri
          value: 'https://managed-identity-wallets-new.stable.demo.catena-x.net/api'
        - name: sdfactory.secret.jwkSetUri
          value: 'https://centralidp.stable.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs'
        - name: sdfactory.secret.realm
          value: <path:essential-services/data/custodian-stable#realm>
        - name: sdfactory.secret.resource
          value: <path:essential-services/data/custodian-stable#resource>
      values: |-
        ingress:
          enabled: true
          className: "nginx"
          issuer: "letsencrypt-prod"
          domain: ""
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/configuration-snippet: |-
              if ($http_origin ~* "http.?:\/\/(.*\.)?(localhost:3000|catena-x\.net|example\.com|idses-fe\.demo\.catena-x\.net).*$") {
                set $allow_origin $http_origin;
              }

              add_header "Access-Control-Allow-Origin" "$http_origin" always;
              add_header "Access-Control-Allow-Methods" "GET, PUT, POST, OPTIONS, DELETE" always;
              add_header "Access-Control-Allow-Headers" "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization" always;
              add_header "Access-Control-Expose-Headers" "Content-Range";

              if ($request_method = 'OPTIONS') {
                add_header "Access-Control-Allow-Origin" "$http_origin" always;
                add_header "Access-Control-Allow-Methods" "GET, PUT, POST, OPTIONS, DELETE" always;
                add_header "Access-Control-Allow-Headers" "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization" always;
                add_header "Access-Control-Max-Age" "1728000" always;
                add_header "Content-Type" "text/plain charset=UTF-8";
                add_header "Content-Length" 0;
                return 204;
              }

          hosts:
            - host: "sdfactory-23-12.stable.demo.catena-x.net"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - tlsName: sdfactory-23-12.stable.demo.catena-x.net-tls
              hosts:
                - sdfactory-23-12.stable.demo.catena-x.net
