apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-agent
  namespace: argocd
spec:
  project: project-knowledge
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-knowledge
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 1.9.8
    chart: provisioning-agent
    plugin:
      env:
        - name: HELM_VALUES
          value: |
            securityContext:
              readOnlyRootFilesystem: false
              runAsUser: 999
              runAsGroup: 999
              runAsUser: 999
            podSecurityContext:
              runAsGroup: 999
              fsGroup: 999
            bindings:
              dtc:
                port: 8080
                settings:
                    jdbc.url: "jdbc:h2:file:/opt/ontop/database/db;INIT=RUNSCRIPT FROM '/opt/ontop/data/dtc.sql'"
                    jdbc.driver: "org.h2.Driver"
                    ontop.cardinalityMode: "LOOSE"
                mapping: |
                  [PrefixDeclaration]
                  cx-common:          https://w3id.org/catenax/ontology/common#
                  cx-core:            https://w3id.org/catenax/ontology/core#
                  cx-vehicle:         https://w3id.org/catenax/ontology/vehicle#
                  cx-reliability:     https://w3id.org/catenax/ontology/reliability#
                  uuid:               urn:uuid:
                  bpnl:               bpn:legal:
                  owl:                http://www.w3.org/2002/07/owl#
                  rdf:                http://www.w3.org/1999/02/22-rdf-syntax-ns#
                  xml:                http://www.w3.org/XML/1998/namespace
                  xsd:                http://www.w3.org/2001/XMLSchema#
                  json:               https://json-schema.org/draft/2020-12/schema#
                  obda:               https://w3id.org/obda/vocabulary#
                  rdfs:               http://www.w3.org/2000/01/rdf-schema#
                  oem:                urn:oem:

                  [MappingDeclaration] @collection [[
                    mappingId dtc-meta
                    target    bpnl:{bpnl} rdf:type cx-common:BusinessPartner ; cx-core:id {bpnl}^^xsd:string .
                    source    SELECT distinct "bpnl" FROM "dtc"."meta"

                    mappingId dtc-content
                    target    oem:Analysis/{id} rdf:type cx-reliability:Analysis ; cx-core:id {code}^^xsd:string ; cx-core:name {description}^^xsd:string .
                    source    SELECT * FROM "dtc"."content"

                    mappingId dtc-part
                    target    oem:Part/{entityGuid} rdf:type cx-vehicle:Part ; cx-core:id {enDenomination}^^xsd:string ; cx-core:name {classification}^^xsd:string .
                    source    SELECT * FROM "dtc"."part"

                    mappingId dtc-meta-part
                    target    oem:Part/{entityGuid} cx-vehicle:manufacturer bpnl:{bpnl}.
                    source    SELECT "bpnl","entityGuid" FROM "dtc"."part"

                    mappingId dtc-part-content
                    target    oem:Analysis/{dtc_id} cx-reliability:analysedObject oem:Part/{part_entityGuid}.
                    source    SELECT "part_entityGuid","dtc_id" FROM "dtc"."content_part"

                  ]]
