apiVersion: v2
name: portal
description: PRE-PROD deployment of the portal release
type: application
version: 0.2.0
appVersion: "0.6.0"

dependencies:
  - name: portal
    alias: portal-frontend
    version: 0.6.0
    condition: portal-frontend.enabled
    repository: "https://catenax-ng.github.io/product-portal-cd/"
  - name: portal-backend
    version: 0.6.0
    condition: portal-backend.enabled
    repository: "https://catenax-ng.github.io/product-portal-cd/"
