apiVersion: v2
name: daps-registration-service
description: PRE-PROD deployment of the daps-registration-service release
type: application
version: 0.1.0
appVersion: "1.0.4"

dependencies:
  - name: daps-reg-service
    alias: daps-registration
    version: 1.0.4
    repository: "https://catenax-ng.github.io/product-daps-registration-service/"
