core:
  cxportal:
    portal:
      ingress:
        enabled: true
        tls:
          - hosts:
            - portal-release.int.demo.catena-x.net
            secretName: tls-secret
        hosts:
          - host: portal.pre-prod.demo.catena-x.net
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: registration
                    port: 8080
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /$1
          nginx.ingress.kubernetes.io/use-regex: "true"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.int.demo.catena-x.net"
