core:
  cxportal:
    portal:
      ingress:
        enabled: true
        tls:
          - hosts:
            - portal.pre-prod.demo.catena-x.net
            secretName: portal.pre-prod.demo.catena-x.net-tls
        hosts:
          - host: portal.pre-prod.demo.catena-x.net
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: registration
                    port: 8080
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /$1
          nginx.ingress.kubernetes.io/use-regex: "true"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.pre-prod.demo.catena-x.net"
