apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bpdm-pool
  labels:
    appVersion_validated: "true"
spec:
  destination:
    namespace: product-bpdm
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 4.3.1
    chart: bpdm-pool
  project: project-bpdm
  syncPolicy:
    automated: {}
