apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daps-server
  labels:
    appVersion_validated: "true"
spec:
  destination:
    name: ''
    namespace: product-essential-services
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 1.7.7
    chart: daps-server
    helm:
      values: |
        image:
          repository: "ghcr.io/fraunhofer-aisec/omejdn-server"
          tag: "1.7.1"
  project: project-essential-services
  syncPolicy:
    automated: {}
