apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: daps-server
spec:
  destination:
    name: ''
    namespace: product-essential-services
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 1.7.2
    chart: daps-server
  project: project-essential-services
  syncPolicy:
    automated: {}
