apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: irs
  labels:
    appVersion_validated: "false"
spec:
  destination:
    namespace: product-traceability-irs
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 5.0.9
    chart: irs-helm
  project: project-traceability-irs
  syncPolicy:
    automated: {}
