apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: managed-identity-wallets
spec:
  destination:
    name: ''
    namespace: product-managed-identity-wallets
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 0.6.3
    chart: managed-identity-wallets
  project: project-managed-identity-wallets
  syncPolicy:
    automated:
