apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sdfactory
  labels:
    appVersion_validated: "false"
spec:
  destination:
    name: ''
    namespace: product-essential-services
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 1.1.1
    chart: sdfactory
  project: project-essential-services
  syncPolicy:
    automated: {}
