apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semantic-hub
  labels:
    appVersion_validated: "true"
spec:
  destination:
    namespace: product-semantics
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 0.1.3
    chart: semantic-hub
    helm:
      parameters:
        - name: "hub.imagePullSecrets[0].name"
          value: "machineuser-pull-secret-ro"
        - name: "hub.image"
          value: "ghcr.io/catenax-ng/semantic-hub:0.1.0-M2"
  project: project-semantics
  syncPolicy:
    automated: {}
