apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: digital-twin-registry
  labels:
    appVersion_validated: "true"
spec:
  destination:
    namespace: product-semantics
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 0.2.3
    chart: registry
    helm:
      parameters:
      - name: "registry.imagePullSecrets[0].name"
        value: "machineuser-pull-secret-ro"
      - name: "hub.image"
        value: "ghcr.io/catenax-ng/registry:0.2.0-M3-multi-tenancy"
  project: project-semantics
  syncPolicy:
    automated: {}
