apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traceability-foss-frontend
  labels:
    appVersion_validated: "false"
spec:
  destination:
    namespace: product-traceability-foss
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 1.1.0
    chart: tx-traceability-foss-frontend
  project: project-traceability-foss
  syncPolicy:
    automated: {}
