apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tractusx-connector
spec:
  destination:
    namespace: product-edc
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://eclipse-tractusx.github.io/charts/dev'
    targetRevision: 0.3.3
    chart: tractusx-connector
  project: project-edc
  syncPolicy:
    automated: {}
