apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sd-factory
spec:
  project: project-sd-factory
  source:
    repoURL: 'https://github.com/catenax-ng/catena-x-release-deployment'
    path: pre-prod/sd-factory
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-sd-factory
  syncPolicy:
    automated: {}
