apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semantic-hub
spec:
  project: project-semantic-hub
  source:
    repoURL: 'https://github.com/catenax-ng/catena-x-release-deployment'
    path: pre-prod/semantic-hub
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin-helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: product-semantic-hub
  syncPolicy:
    automated: {}
