semantic-hub:
  hub:
    image: ghcr.io/catenax-ng/semantic-hub:0.1.0-M2
    imagePullSecrets:
      - name: machineuser-pull-secret-ro
    containerPort: 4242

    host: semantics.pre-prod.demo.catena-x.net

    idpIssuerUri: <path:semantics/data/authentication#keycloak-idp-preprod>
    idpClientId: <path:semantics/data/authentication#idpClientIdHub-preprod>

  ingress:
    urlPrefix: /hub
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
      nginx.ingress.kubernetes.io/x-forwarded-prefix: /hub

  graphdb:
    password: "<path:semantics/data/authentication#graphdbPw-preprod>"
    storageClassName: azurefile
    storageSize: 8Gi
    pvcAccessModes:
      - ReadWriteOnce
