apiVersion: v2
name: iam-centralidp
description: PRE-PROD deployment of the IAM Keycloak Central instance release
type: application
version: 0.2.0
appVersion: "0.7.0"

dependencies:
  - name: centralidp
    version: 0.7.0
    condition: centralidp.enabled
    repository: "https://catenax-ng.github.io/product-portal-iam/"
