apiVersion: v2
name: iam-centralidp
description: PRE-PROD deployment of the IAM Keycloak Central instance release
type: application
version: 0.1.0
appVersion: "0.5.3"

dependencies:
  - name: centralidp
    version: 0.5.3
    condition: centralidp.enabled
    repository: "https://catenax-ng.github.io/product-portal-iam/"
