apiVersion: v2
name: bpdm
description: PRE-PROD deployment of the bpdm release
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: bpdm
    condition: bpdm.enabled
    version: 2.0.0
    repository: "https://catenax-ng.github.io/product-bpdm/"
