daps:
  ingress:
    enabled: true
    host: daps.pre-prod.demo.catena-x.net
    pathPrefix: "/"
    rootPath: "/"
    tls:
      enabled: true
      certMgr:
        enabled: true
        issuer: "letsencrypt-prod"
  daps:
    secret:
      clientId: "<path:essential-services/data/daps-preprod#clientId>"
      clientSecret: "<path:essential-services/data/dapspre-prod#clientSecret>"
