apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-release
spec:
  project: default
  source:
    repoURL: 'https://github.com/catenax-ng/catena-x-release-deployment'
    path: pre-prod/chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: core
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
